"""add_search_status

Revision ID: 7e63e4387b7d
Revises: c37f68451213
Create Date: 2026-09-27 14:22:46.841296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e63e4387b7d'
down_revision: Union[str, None] = 'c37f68451213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('searches', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('searches', 'status')
    # ### end Alembic commands ###
