"""add_search_dashboard_data

Revision ID: a5eddaf1fd2c
Revises: 93d6efe3daa8
Create Date: 2026-09-27 15:01:49.603298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5eddaf1fd2c'
down_revision: Union[str, None] = '93d6efe3daa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('searches', sa.Column('dashboard_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('searches', 'dashboard_data')
    # ### end Alembic commands ###
